import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 10.0
normal = { family = "Hack Nerd Font" }

[window]
decorations = "Buttonless"
opacity = 0.85
padding = { x = 12, y = 12 }
